### ISSUE TITLE
return expression of async function is not showing coverage

### ISSUE THREAD

**Issue by tikotzky** [ambitioninc/babel-istanbul#16]
if you test the following code...
```js
async function foo(){
	return 'foo';
}

(async () => {
	let result = await foo();
	console.log(result);
})();

```
the coverage comes out looking like
![index js 2015-06-21 21-15-34](https://cloud.githubusercontent.com/assets/200528/8274223/1ec2c612-185b-11e5-894b-c083f2fd5725.jpg)

**Comment by Swatinem** [comment]
It works for me now after #15. However, the console.log after the await is not called for me (I don’t see the log when i run it with babel-istanbul cover)

**Comment by jmcriffey** [comment]
@Swatinem What are you using to actually run the tests? You might be exiting before the log statement is hit.

**Comment by Swatinem** [comment]
just `babel-istanbul cover --babel-stage 1 --use-babel-runtime test.js` with the code pasted in. So yes, I do think that it exits before the log (or even before returning from the await)

**Comment by tikotzky** [comment]
@Swatinem do you get the log in your console?

**Comment by tikotzky** [comment]
just ran it again and it looks good now.

![index js 2015-06-22 14-51-26](https://cloud.githubusercontent.com/assets/200528/8290019/34657b2a-18ee-11e5-864b-f63c3775c224.jpg)
