### ISSUE TITLE
Unexpected Class Branch Coverage

### ISSUE THREAD

**Issue by bassettsj** [ambitioninc/babel-istanbul#17]
Hey great work no getting this out!

I am getting unexpected coverage reported:

![Screenshot showing branch coverage](https://cloud.githubusercontent.com/assets/1218420/8419497/018cdd02-1e6f-11e5-89fe-22ed68bf9d17.png)

It is showing that the "else" paths are not being taken here.

**Comment by jmcriffey** [comment]
Maybe try adding the `--use-babel-runtime` flag. That will tell the compiler to use the helper library instead of defining functions at the top of every file.

**Comment by bassettsj** [comment]
@jmcriffey  Sorry I messed up the integration with karma and browserify. It is fine after all.
