### ISSUE TITLE
istanbul ignore next isn't working

### ISSUE THREAD

**Issue by jonathanong** [ambitioninc/babel-istanbul#2]
example: https://github.com/jonathanong/babel-istanbul-test

https://travis-ci.org/jonathanong/babel-istanbul-test

should have 100% coverage

**Comment by jmcriffey** [comment]
I'll look into debugging this ASAP. There is definitely something weird with the way I am compiling and that is not ideal.

On another note, you are liking going to run into trouble down the road using iojs and this tool together. Tests should be run using babel-node or just code compiled by babel. You'll be running code that is not compiled during your tests with iojs and istanbul is going to be referencing compiled code. I'm not sure what will break, but something almost definitely will.

**Comment by jonathanong** [comment]
i'm mostly using babel for the better esprima support because I use basically all the es6 features in io.js, but esprima nor esprima-harmony can really handle it. hacky, yes. hoping istanbul uses babel as the transpiler or something.

**Comment by Swatinem** [comment]
isparta has the same issue. But I see you bumped the babel dep, so maybe I can switch over.

**Comment by jmcriffey** [comment]
@jonathanong @Swatinem This is actually a weird combo of babel doing weird stuff and istanbul doing weird stuff. I'll try to break it down.

Istanbul seems to fail ignoring if the comment is not separated by spaces on the right from other code. For an example:
```js
//this fails
doSomething(/* istanbul ignore next */function () {
});

//this succeeds
doSomething(/* istanbul ignore next */ function () {
});
```

The only difference in failing and succeeding to ignore above is the space before the function keyword. Unfortunately, babel strips all spaces between the comment and the function keyword when you compile. While babel's behavior is not ideal, I think istanbul itself is at fault for the bug. I'll see if I can get some help with istanbul's behavior.

For the short term, you can fix problems like your example by putting ignore comments on their own line:

```js
'use strict';

module.exports = function () {
    return Promise.resolve(true).catch(
        /* istanbul ignore next */
        function (err) {
            console.error('this should be ignored');
        }
    );
}
```
