### ISSUE TITLE
Are there plans to provide gulp package?

### ISSUE THREAD

**Issue by gajus** [ambitioninc/babel-istanbul#23]
It would be nice to be able to run babel-istanbul using gulp.

**Comment by jmcriffey** [comment]
We don't currently have any plans to build plugins for package managers around babel-istanbul. I would encourage you to look into building one and releasing it.

**Comment by gajus** [comment]
Ok, I will do it, https://github.com/gajus/gulp-babel-istanbul.

It should be done before the end of the week.

**Comment by jmcriffey** [comment]
Great, I'll add a link to the readme once it is finished. Thanks!
