### ISSUE TITLE
Doesn't work with harmony proxies

### ISSUE THREAD

**Issue by dphaener** [ambitioninc/babel-istanbul#29]
This is more of a call for help rather than an issue. I have a testing library that I use that uses harmony proxies. It looks like this needs to be enabled, but I haven't figured out how to run the coverage with harmony proxies enabled. Any ideas?

**Comment by jmcriffey** [comment]
Babel doesn't and can't support proxies due to the limitations of ES5. You'll likely have to wait until istanbul itself can cover proxies, which might be a long while.

**Comment by jmcriffey** [comment]
Just for reference: https://babeljs.io/docs/learn-es2015/#proxies

**Comment by dphaener** [comment]
Yeah, I know that Babel doesn't support it. Thought maybe there might be some way to run coverage with `node --harmony-proxies`. If not, ah well.

**Comment by jmcriffey** [comment]
I actually don't see why istanbul itself wouldn't work with proxies since there is not special syntax involved. Have you actually tried running coverage with node and harmony proxies?

**Comment by dphaener** [comment]
I've tried, but I fear that I don't have the syntax correct.
