### ISSUE TITLE
Upgrade to which 1.2

### ISSUE THREAD

**Issue by isaacs** [ambitioninc/babel-istanbul#31]
Fix for https://github.com/npm/node-which/issues/21

Thanks.

**Comment by isaacs** [comment]
Note: you can do this pretty easily by running the following commands:

```bash
npm i which@latest -S
git add package.json
git commit -m "upgrade 'which' module"
npm version patch
npm publish
git push origin master
```

There have been no significant changes to the API between 1.1 and 1.2, except making the bin match the output, options, and exit code of BSD's builtin `which(1)`, which probably it should have always done.

**Comment by jmcriffey** [comment]
I'll bump it here, but it might also be worth opening the same issue on the main istanbul repo.

**Comment by jmcriffey** [comment]
Should be updated in 0.4.1, thanks!

**Comment by isaacs** [comment]
The main istanbul repo depends on `^1.1.1`, so that'll pick up `1.2.0` by default.

Thanks for landing this!
