### ISSUE TITLE
Can't run "babel-node" from package.json script

### ISSUE THREAD

**Issue by imposibrus** [ambitioninc/babel-istanbul#35]
// "i-dont-speak-english" mode on

https://babeljs.io/blog/2015/10/31/setting-up-babel-6/
> The `babel` package is no more.
> Now we’ve split it up into two separate packages: `babel-cli` and `babel-core`.

Right now `babel` package has bin file `babel-node` with deprecation warning (and just `process.exit();`). Therefore i can't use following code in package.json:
```
...
"scripts": {
    "coverage": "babel-node node_modules/.bin/babel-istanbul cover node_modules/mocha/bin/_mocha -- --reporter dot"
}
...
```
Also i can't use absolute path to globally installed `babel-node` (different environments, etc.).
Temporary workaround is install `babel-cli` locally. But i think that replace dependency `babel` on `babel-core` it's necessary.

// "i-dont-speak-english" mode off

**Comment by jmcriffey** [comment]
You'll have to install and use `babel-cli` in your project. That has been working well for me. They simply moved the babel-node bin to a new repository. This project never explicitly tells you to use babel-node, it is for you to decide how you want to run your tests.
