### ISSUE TITLE
No coverage information was collected, exit without writing coverage information && ERROR: No coverage files found.

### ISSUE THREAD

**Issue by kennetpostigo** [ambitioninc/babel-istanbul#36]
Hello,
Im currently trying to implement babel-istanbul with travis, codecov, and ghooks. But I keep getting the errors that no coverage information is being collected. I'm not sure why. I've been attempting to get this to work and have looked through tons of articles and gists, but none help me out. 

This is package.json file:
<img width="828" alt="screen shot 2015-11-15 at 8 18 54 pm" src="https://cloud.githubusercontent.com/assets/8888991/11172492/2c6c5cd0-8bd6-11e5-88a2-433a8317bb83.png">

This is what happens when I run the `test:single`(at the end it says "No coverage information was collected, exit without writing coverage information"):
<img width="661" alt="screen shot 2015-11-15 at 8 19 57 pm" src="https://cloud.githubusercontent.com/assets/8888991/11172523/d5c05a0c-8bd6-11e5-9f2c-3b2cb60a344c.png">

This is what happens when I run check-coverage to check the quality with babel-istanbul:
<img width="949" alt="screen shot 2015-11-15 at 8 20 11 pm" src="https://cloud.githubusercontent.com/assets/8888991/11172525/ee4463ac-8bd6-11e5-8333-8de74c6ee296.png">

I really hope someone can help me out, any and all help & feedback is very much appreciated.

**Comment by noamshemesh** [comment]
:+1: I'm encountering the same issue

**Comment by jmcriffey** [comment]
To my knowledge: istanbul has never worked with mocha when using compilers. Try running your tests with babel-istanbul.

**Comment by lfilho** [comment]
@jmcriffey how so?
I've tried: 
`babel-node node_modules/istanbul/lib/cli.js cover node_modules/mocha/bin/_mocha -- test --recursive --compilers js:babel-core/register`
But it didn't work: same error `No coverage information was collected, exit without writing coverage information` appears. :(

**Comment by jmcriffey** [comment]
@lfilho You CANNOT use `--compilers js:babel-core/register`. That is causing another process to be spawned and istanbul cannot read coverage from it. Remove that part and see if it starts working.

```
babel-node node_modules/babel-istanbul/lib/cli.js cover node_modules/mocha/bin/_mocha -- test --recursive
```

**Comment by kennetpostigo** [comment]
Hey guys I was able to get it up and running :)

**Comment by lfilho** [comment]
@jmcriffey that's right! Now it works! Thanks!

**Comment by lfilho** [comment]
I miss the `--print both` option though :( :innocent:
