### ISSUE TITLE
How to use it with custom test runner

### ISSUE THREAD

**Issue by kilianc** [ambitioninc/babel-istanbul#45]
I have a `runner.js` with `require('babel-register')` at the top and mocha used programmatically. I run my test suite with:

    $ node test/runner.js

so far 

    $ node_modules/.bin/babel-istanbul cover test/runner.js

hasn't been successful

**Comment by jmcriffey** [comment]
I believe requiring `babel-register` is your problem. Try removing that require statement and run your tests with `babel-node` instead of `node`.

`babel-node node_modules/.bin/babel-istanbul cover test/runner.js`

**Comment by kilianc** [comment]
@jmcriffey yeah using `babel-node` does it. It would be interesting to understand why it does. It should do pretty much the same thing right ?

**Comment by jmcriffey** [comment]
The reason has to do with how `babel-register` works. They used to have a patch specifically for this use case but took it out in version 6.
