### ISSUE TITLE
Weird stuff, semicolon at end of statement treated as branch

### ISSUE THREAD

**Issue by silkentrance** [ambitioninc/babel-istanbul#46]
In my project, I have a weird problem that will treat semicolons at the end of the statement as separate branches.

I am using babel 6.3.19 and babel-istanbul 0.5.9.

Here is an excerpt from the generated coverage report

```
1            let target = args[0];
 
            // we do not support constructor injection
            if (args.length == 1)
            {
                util.log(
                    messages.MSG_USE_PROPERTY_INJECTION_INSTEAD,
                    target, null, ifaces, logger.error
                );
 
                throw new InjectionError(
                    messages.MSG_USE_PROPERTY_INJECTION_INSTEAD
                );
            }
 
2            const attr = args[1];
3            const descriptor = args[2];
```

Where (1) to (3) will cause missing coverage due to the ``;`` not being covered.

You can check this out yourself: https://github.com/coldrye-es/inxs.git

Simply run (on preferably a new VM running debian/stretch)

```
make deps-global
make deps
make cover
```

The coverage report will be available under ./build/cover/index.html. Navigating to src/inxs.es will give you that information.

**Comment by silkentrance** [comment]
Even more weird is, that when I remove the trailing semicolons, the coverage report will still be the same.

**Comment by jmcriffey** [comment]
You'll want to look at the transpiled code to see what babel might be sticking in there to make your coverage fail. This doesn't have anything to do with the semicolons, as there is probably just a branch of code hidden in the transpiled version.

If you are messing around with the arguments object in this method above, babel is likely injecting a branch of code to check something for compatibility. If you can show me the source and then the compiled code next to each other, I might be able to help you out more. Every now and then babel produces some code that just has to be skipped in coverage for one reason or another.

**Comment by silkentrance** [comment]
Yes, you are right. I've made istanbul ignore the specific statements for the time being. Thanks!
