### ISSUE TITLE
How do I use babel-instabul with karma?

### ISSUE THREAD

**Issue by fernandofleury** [ambitioninc/babel-istanbul#47]
Greetings. I would like to use it with karma. By default karma-coverage works with istanbul. Is there anything I could do in order to use babel-instanbul instead?

**Comment by jmcriffey** [comment]
I'm not sure how `karma-coverage` works, but `babel-istanbul` is a drop in replacement for `istanbul`. If you can figure out how `karma-coverage` plugs in with `istanbul`, then you should be able to simply replace it.

**Comment by mmahalwy** [comment]
Any luck with this @fernandofleury ?

**Comment by fernandofleury** [comment]
@mmahalwy I've moved to https://github.com/deepsweet/babel-istanbul-loader
