### ISSUE TITLE
When instrumenting files with extension .es6 the instrumented files will have the same extension

### ISSUE THREAD

**Issue by silkentrance** [ambitioninc/babel-istanbul#6]
Would it be possible to replace the existing extension with .js as is the standard behavior when calling babel directly to transform a given suite of sources?

**Comment by jmcriffey** [comment]
I'm not sure what you mean. Could you explain more?

**Comment by silkentrance** [comment]
I see that this is the standard istanbul behavior. Sigh, will rename my sources and use the .es6.js extension instead.
